#!/bin/bash

file_name="*\\\\\\'\"Best School\"\\'\\\\\\*\\$\\?\\*\\*\\*\\*\\*:)"

echo "Best School" > "$file_name"
echo "" >> "$file_name"

echo "File '$file_name' created with content 'Best School' and a new line."


